# The number of controllers and agents to run. A minimum of 1 is
# set for testing purposes but more should be used in production for high availability.
replicaCount: 1

image:
  # The image repository to pull from
  repository: ngrok/ngrok-ingress-controller
  # The image tag to pull
  tag: latest
  # The image pull policy
  pullPolicy: IfNotPresent

# The ingress class this controller will satisfy. If not specified, controller will match all
# ingresses without ingress class annotation and ingresses of type ngrok
ingressClass: ngrok

# This is the URL of the ngrok server to connect to. You should set this if you are using a custom ingress URL.
serverAddr:
# ngrok region to create tunnels in.
region:

# The name of the K8S secret that contains the credentials for the
# ingress controller.
credentials:
  secret:
    create: false
    name: ngrok-ingress-controller-credentials
  apiKey: ""
  authtoken: ""

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# Used to inject custom annotations directly into the ingress pods for things like service mesh integrations.
podAnnotations: {}