apiVersion: v1
kind: ConfigMap
metadata:
  name: ngrok-ingress-controller-agent-cm
  namespace: {{ .Release.Namespace }}
data:
  SERVER_ADDR:  "{{ .Values.serverAddr }}"
  METADATA: "{{ .Values.metaData }}"
  REGION: "{{ .Values.region }}"
  REMOTE_MANAGEMENT: "{{ .Values.remoteManagement }}"
