{{- if or (not (empty .Values.apiKey)) (not (empty .Values.authtoken)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentialsSecret.name }}
type: Opaque
data:
  API_KEY: {{ required "An ngrok API key is required" .Values.apiKey | b64enc }}
  AUTHTOKEN: {{ required "An ngrok Authtoken is required" .Values.authtoken | b64enc }}
{{ end }}
