{{- if or .Values.apiKey .Values.authToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentialsSecretName.name }}
type: Opaque
data:
  API_KEY: {{ .Values.apiKey | b64enc }}
  AUTHTOKEN: {{ .Values.authToken | b64enc }}
TODO: Conditionally add this if both the api key and auth token are passed in as keys
{{ end }}
